services:
  postgres:
    image: postgres:16-alpine
    container_name: netmu-pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: netmu
    ports:
      - "5432:5432"
    volumes:
      - netmu-pg-data:/var/lib/postgresql/data

volumes:
  netmu-pg-data:
